### ISSUE TITLE
can't load any network

### ISSUE THREAD

**Issue by vogt31337** [Tooblippe/pandapower_gui#10]
Just crashes with:

Inialise Collections
{'load2': <matplotlib.collections.LineCollection object at 0x000000000D81A5C0>, 'ext_grid1': <matplotlib.collections.PatchCollection object
at 0x0000000000AAB6D8>, 'trafo1': <matplotlib.collections.LineCollection object at 0x000000000B338908>, 'load1': <matplotlib.collections.Pat
chCollection object at 0x000000000D556DA0>, 'bus': <matplotlib.collections.PatchCollection object at 0x000000000D81A390>, 'ext_grid2': <matp
lotlib.collections.LineCollection object at 0x000000000D81A198>, 'line': None, 'trafo2': <matplotlib.collections.PatchCollection object at 0
x000000000D81A748>}
Drew Collections
Inialise Collections
{'load2': <matplotlib.collections.LineCollection object at 0x000000000DA62BA8>, 'ext_grid1': <matplotlib.collections.PatchCollection object
at 0x000000000D81A7B8>, 'trafo1': <matplotlib.collections.LineCollection object at 0x000000000D5BD9B0>, 'load1': <matplotlib.collections.Pat
chCollection object at 0x000000000DA42710>, 'bus': <matplotlib.collections.PatchCollection object at 0x000000000DA55080>, 'ext_grid2': <matp
lotlib.collections.LineCollection object at 0x000000000DA62E48>, 'line': None, 'trafo2': <matplotlib.collections.PatchCollection object at 0
x000000000DA55978>}
Drew Collections
Traceback (most recent call last):
  File "pandapower_gui.py", line 234, in mainLoadClicked
    self.load_network(net)
TypeError: load_network() missing 1 required positional argument: 'name'

**Comment by lthurner** [comment]
This repository is not under development any more, development is continued here: https://github.com/e2nIEE/pandapower-gui
